### ISSUE TITLE
Hiboutik ZPL Datamatrix Barcode Label Print

### ISSUE THREAD

**Issue by finepos** [hiboutik/hiboutikapi#1]
Hi!
Now we use this ZPL code for mark our products:
Label 40*25mm
==============================

^XA
^PQ1
^FO70,40^A0N,20,20^FDWWW.PRINTEC.COM.UA^FS
^FO70,75^A0N,20,20^FD+38 (093) 333 0 777^FS
^FO5,40
^BXN,4,200,,,,,1
^FD{barcode}
^FS
^FO1,8^A0N,18,18^FD{name}^FS
^FO5,110^BY2
^BCN,50,Y,N,N
^FD{barcode}^FS
^XZ

==============================
Where:
{name} - Product Name
{barcode} - Product Barcode
==============================

If we use <hibou_print_zpl_bar_code> - instead our {barcode} - we received error printing, because Your parameter get started print You barcode type.
But we used CODE128 and Datamatrix on one label.

Please add parameter (FOR SAMPLE)<hibou_print_zpl_products_barcode>, Which will return the value of the barcode field in the product map.

![0-02-04-9d57a74ff94e0fd7c4b4ecfaa9ed96c6bd787af720167220e54ac016b9f51014_full](https://user-images.githubusercontent.com/17965327/29402780-dbc6b2aa-833e-11e7-8c9a-ce1bb7418ba5.jpg)

**Comment by hiboutik** [comment]
Hi,

As this is not related to Hiboutik API, please use the following URL to contact the team in charge of label printing : https://www.hiboutik.com/en/contact/

To answer your question, you can use <hibou_print_zpl_bar_code_value>.

Sincerely

**Comment by finepos** [comment]
Now we test this parameter <hibou_print_zpl_bar_code_value>
it also start to print CODE128 command.

For our labels we need only value of barcode field, which will return the value of the barcode field in the product map.

For example, if we used parameter <hibou_print_zpl_products_name> - it return product name and we received good result

**Comment by hiboutik** [comment]
As this is not related to Hiboutik API, please use the following URL to contact the team in charge of label printing : https://www.hiboutik.com/en/contact/
