### ISSUE TITLE
Using hiboutik api in JavaScript React app

### ISSUE THREAD

**Issue by mbcod3** [hiboutik/hiboutikapi#14]
I want to use hiboutik api in React app. Since hiboutik api requires php, is there a way to use in JavaScript app?

**Comment by hiboutik** [comment]
Hi, you cannot use this package directly in your app. You would need to implement it in JavaScript.
Since you're dealing with an API you can use the whatever language you wish on your side. It just has to send the right headers and fields.
The other way to do it would be to create an endpoint on your server which uses PHP and communicate with it via AJAX requests.
 
Cheers

**Comment by mbcod3** [comment]
But the github doc has php requirement. Can you send me page with example
for api to get client loyalty points displayed on my website?

Thanks a lot

**Comment by hiboutik** [comment]
There's no JavaScript implementation for now but here's a quick example:
`
var account = 'my_hiboutik_account';
var user = 'user@exemple.com';
var api_key = 'SDJKFH08743GHLSI8FAY3PO498TY389RG)';

var my_customer = 2;
var url = 'https://' + account + '.hiboutik.com/api/customer/' + my_customer;

request = new XMLHttpRequest();
request.onreadystatechange = function () {
  if (this.readyState === 4) {
    if (this.status === 200 || this.status === 201) {
      var response = JSON.parse(this.responseText);
      console.log('Loyalty points: ' + response[0].loyalty_points);
    } else {
      console.log('API error:', this);
    }
  }
}
request.responseType = 'application/json';
request.open("GET", url, true);
request.setRequestHeader('Authorization', 'Basic ' + btoa(user + ':' + api_key));
request.send();
`

**Comment by mbcod3** [comment]
Thank you for your quick response. I appreciate your help.
I created Hiboutik account for api testing. I have few questions.

1. What do put in the place of 'my_hiboutik_account'? In general settings I
have

testingapi77 (company name I entered during signup)
ID: 7788361
Host: m6.hiboutik.net

2. var user = "email address", is it admin email address?

3. Where do I get my api key? I can't find in the dashboard in demo mode.

4. var my_customer = 2; Is this customer id? Second customer gets 2 as id
and so on. If so how can a user himself see his loyalty point on the
website? He wouldnt know his id in the hiboutik platform.

**Comment by hiboutik** [comment]
1. my_hiboutik_account.hiboutik.com -> testingapi77
2. email used for your hiboutik account
3. settings -> users -> users -> wrench icon
4. use the API, mbcod3 (https://testingapi77.hiboutik.com/docapi/)

Should you have any more questions address them to the Hiboutik customer service, they will be answered in a timely manner.
I'm closing this issue as there's nothing wrong with the code.

Cheers
