### ISSUE TITLE
Little installation troubles / updates to do in README (?)

### ISSUE THREAD

**Issue by Kaddath-R** [hiboutik/hiboutikapi#2]
Hi!

  I just managed to make all this working, and i think that either there is a problem with Composer dependencies, either the explanation is not clear and i missed one step. Anyway, the README might need a little update, seemingly because "php-curl-class" had some changes (maybe that is the source or the problem i had with the Composer install?).

COMPOSER INSTALLATION:
_If i didn't miss any step, there is a problem with dependencies: when i ran the Composer command, it successfully installed the dependency [ - Installing php-curl-class/php-curl-class (2.0.0): Downloading (100%)]. However, when testing the script, i had this error: "PHP Fatal error:  Class 'Curl\Curl' not found in /srv/data/web/vhosts/v2.tir81.fr/vendor/hiboutik/hiboutikapi/lib/Hiboutik/HiboutikAPI.php on line 158".

MANUAL INSTALLATION:
_I then tried manual installation, as i saw this class was present in the includes (at this point i was not sure if "manual installation" was the normal step to do after Composer, or an alternative way to install, that also could be clearer).
_this led to this error: "PHP Fatal error:  Uncaught Error: Class 'Curl\Url' not found in /srv/data/web/vhosts/v2.tir81.fr/htdocs/neoHiboutikClasses/Curl.php:1085". I noticed that you are talking about the "three files", but when i dowloaded "php-curl-class", i saw there are 7 files and not 3. After different tests, including all the 7 files made it work.

Only after i had all this working, i noticed that when including "HiboutikAPI.php", i didn't need Composer at all anymore, and that the include way was working on its own (which is a bit deceiving in a way, I lost a good amount of time getting Composer to work on my hosting, to realize that it's not needed at all, it probably shouldn't be in the Requirements actually).

Thanks for this tool by the way, excepting these installation problems, it seems to work great and easy to use!
Kaddath

**Comment by hiboutik** [comment]
Hello,

Thanks for your input and sorry for the lost time.
Indeed, it's one of the two installation methods: either with composer, either manual. We will clarify that in the documentations.
It's true that we haven't checked the last version of php-curl-class. There will be an update very soon.

Hiboutik

**Comment by Kaddath-R** [comment]
No problem, that is never really lost, as i learnt new things in the process ;)

Thanks for the answer, and for the plugin, works perfect once installed performed
