### ISSUE TITLE
Include related objects in full list type calls to reduce number of necessary API calls

### ISSUE THREAD

**Issue by tkoopa** [hiboutik/hiboutikapi#6]
For 1:n relations at least ( where currently there is a xxx_id type field ); the methods that return full lists if objects should include the related objects in order to reduce the amount of further API calls ( for better performance and help stay under the number of API calls limit )

eg: when calling the `/products/` the related tags are not included which forces us to make a call to the `/products_tags/{id}` of every product to produce a complete export of the product data ( for label printing ). 
Another case would be when calling `/closed_sales/` include the related `customer` object, `products`, ...

**Comment by hiboutik** [comment]
It will be available for the next release of the API (this summer)
